import { Anek_Bangla } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import { Toaster } from 'sonner';
import FontResizeProvider from '@/context/FontResizeContext';
import SettingBar from '@/components/settingBar/SettingBar';
import SideBarsProvider from '@/context/SideBarsContext';

const anekBangla = Anek_Bangla({
  variable: '--anek-bangla',
  subsets: ['bengali'],
});

export const metadata = {
  title: 'Daily Talim',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo_dark.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="bn" suppressHydrationWarning>
      <body className={`${anekBangla.className} antialiased`}>
        <ThemeProvider
          defaultTheme="system"
          enableSystem={true}
          attribute="class"
          themes={['light', 'dark', 'warm']}
          disableTransitionOnChange
        >
          <main>
            <SideBarsProvider>
              <FontResizeProvider>
                {children}
                <SettingBar />
              </FontResizeProvider>
            </SideBarsProvider>
          </main>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
